### ISSUE TITLE
Flattening multiple APP1 Exif markers in JPEGs

### ISSUE THREAD

**Issue by julik** [remvee/exifr#63]
We are using exifr with a big number of files, and one of the things we see relatively often is multiple APP1 markers in JPEGs. I believe multiple APP1 markers get used to avoid overwriting the original Exif tag because the image dimensions (or some properties) have changed during editing - so editors just slap another APP1 on top describing their changes.

We have recently modified our parsing so that there is some flattening going on when multiple EXIF frames are in the JPEG. It seems that multiple apps - including the macOS Finder - actually "overlay" the metadata bits that come later on top of the ones that come earlier. So for example, when there are multiple APP1 markers and one of them specifies the author and lens information, it is retained in the final "flat" output. When a subsequent APP1 marker also specifies the same properties they get applied "on top" and take precedence.

From what I can see, the APP1 marker handling in exifr (which we do not use - we feed it the extracted APP1 markers ourselves) uses the first APP1 marker that contains Exif. But if that limitation is lifted - is there any idea how to correctly "flatten" multiple bits of EXIF data attached to the same image? Only checking for "the first non-nil value of a given property" is not sufficient. For example, in case of `#orientation` the orientation will be returned as 0 from the last EXIF frame, whereas the 0 actually means "unknown" - the frame preceding it has to be scanned instead. For now I have implemented a workaround, but it probably would be great to provide something in exifr itself to perform data flattening for those situations.

**Comment by remvee** [comment]
Interesting.  Can you supply images (free to use for unit tests) to illustrate this?

**Comment by julik** [comment]
It is a bit hard to do because we deal with user's data - I am not at liberty to just share it. But you can simulate this if you craft a JPEG with two APP1 frames and see what happens, fairly easily. I will trawl my own machine if I have anything of that nature that has multiple APP1 frames, maybe I'll find something.

**Comment by julik** [comment]
I think this file is a good example - https://github.com/WeTransfer/format_parser/commits/master/spec/fixtures/JPEG/orient_6.jpg at least that is what we test with

**Comment by remvee** [comment]
That image doesn't exhibit the behaviour you've mentioned above.  The second APP1 frame only contains the following:

```
              width = 2500
             height = 1250
               bits = 8
        color_space = 1
  pixel_x_dimension = 2500
  pixel_y_dimension = 1250
```

This image is used as a test case for fastimage (issue https://github.com/sdsykes/fastimage/issues/102) which would use the last APP1 instead of the first as EXIFR does.

I am especially curious above a case where "orientation" is "0" in the second frame because, as you have pointed out, some kind of merge logic needs to be implemented to support such cases.  I've just looked at exiftool to see how they implement this and they seem to use a priority flag to avoid overriding (https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/README#L458) tags from earlier frames.  That might be the best way to go but I would like to have test cases to support that.

**Comment by remvee** [comment]
@julik closing this, please reopen it if you can provide a test case.
